sudo: false

language:
  - python

python:
  - 3.7

install:
  - pip install -r requirements.txt

script:
  - black --check promsql
  - pytest --verbose --capture=no tests
  - pip install .

notifications:
  email: false
